#undef fgm_shape_name
#undef fgm_shape_loco_name
#undef fgm_shape_instance_data
#undef fgm_shape_manual_properties
#undef fgm_dont_init_shape
#undef fgm_make_clear_f
#undef fgm_no_gui_properties
#undef fgm_shape_non_moveable_or_resizeable