/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2020-08-31-4a11a6f"
#endif /* AVUTIL_FFVERSION_H */
