#include <fan/types/dme.h>

#define DME_VERIFY_PRINT 1

#if DME_VERIFY_PRINT == 1
#include <stdio.h>
#endif

#define VERIFY_DME 1

#if VERIFY_DME == 1
#include <cassert>
#endif


#pragma pack(push, 1)

struct data_we_want_t {
  int number;
};

struct dme_t : dme_inherit__(dme_t, data_we_want_t) {
  __dme2(a) = {{.number = 5}};
  __dme2(b) = {{.number = 5}};
  __dme2(c) = {{.number = 5}};
  __dme2(d) = {{.number = 5}};
  __dme2(e) = {{.number = 5}};
  __dme2(f) = {{.number = 5}};
  __dme2(g) = {{.number = 5}};
  __dme2(h) = {{.number = 5}};
  __dme2(i) = {{.number = 5}};
  __dme2(j) = {{.number = 5}};
  __dme2(k) = {{.number = 5}};
  __dme2(l) = {{.number = 5}};
  __dme2(m) = {{.number = 5}};
  __dme2(n) = {{.number = 5}};
  __dme2(o) = {{.number = 5}};
  __dme2(p) = {{.number = 5}};
  __dme2(q) = {{.number = 5}};
  __dme2(r) = {{.number = 5}};
  __dme2(s) = {{.number = 5}};
  __dme2(t) = {{.number = 5}};
  __dme2(u) = {{.number = 5}};
  __dme2(v) = {{.number = 5}};
  __dme2(w) = {{.number = 5}};
  __dme2(x) = {{.number = 5}};
  __dme2(y) = {{.number = 5}};
  __dme2(z) = {{.number = 5}};
  __dme2(a1) = {{.number = 5}};
  __dme2(b1) = {{.number = 5}};
  __dme2(c1) = {{.number = 5}};
  __dme2(d1) = {{.number = 5}};
  __dme2(e1) = {{.number = 5}};
  __dme2(f1) = {{.number = 5}};
  __dme2(g1) = {{.number = 5}};
  __dme2(h1) = {{.number = 5}};
  __dme2(i1) = {{.number = 5}};
  __dme2(j1) = {{.number = 5}};
  __dme2(k1) = {{.number = 5}};
  __dme2(l1) = {{.number = 5}};
  __dme2(m1) = {{.number = 5}};
  __dme2(n1) = {{.number = 5}};
  __dme2(o1) = {{.number = 5}};
  __dme2(p1) = {{.number = 5}};
  __dme2(q1) = {{.number = 5}};
  __dme2(r1) = {{.number = 5}};
  __dme2(s1) = {{.number = 5}};
  __dme2(t1) = {{.number = 5}};
  __dme2(u1) = {{.number = 5}};
  __dme2(v1) = {{.number = 5}};
  __dme2(w1) = {{.number = 5}};
  __dme2(x1) = {{.number = 5}};
  __dme2(y1) = {{.number = 5}};
  __dme2(z1) = {{.number = 5}};
  __dme2(a2) = {{.number = 5}};
  __dme2(b2) = {{.number = 5}};
  __dme2(c2) = {{.number = 5}};
  __dme2(d2) = {{.number = 5}};
  __dme2(e2) = {{.number = 5}};
  __dme2(f2) = {{.number = 5}};
  __dme2(g2) = {{.number = 5}};
  __dme2(h2) = {{.number = 5}};
  __dme2(i2) = {{.number = 5}};
  __dme2(j2) = {{.number = 5}};
  __dme2(k2) = {{.number = 5}};
  __dme2(l2) = {{.number = 5}};
  __dme2(m2) = {{.number = 5}};
  __dme2(n2) = {{.number = 5}};
  __dme2(o2) = {{.number = 5}};
  __dme2(p2) = {{.number = 5}};
  __dme2(q2) = {{.number = 5}};
  __dme2(r2) = {{.number = 5}};
  __dme2(s2) = {{.number = 5}};
  __dme2(t2) = {{.number = 5}};
  __dme2(u2) = {{.number = 5}};
  __dme2(v2) = {{.number = 5}};
  __dme2(w2) = {{.number = 5}};
  __dme2(x2) = {{.number = 5}};
  __dme2(y2) = {{.number = 5}};
  __dme2(z2) = {{.number = 5}};
  __dme2(a3) = {{.number = 5}};
  __dme2(b3) = {{.number = 5}};
  __dme2(c3) = {{.number = 5}};
  __dme2(d3) = {{.number = 5}};
  __dme2(e3) = {{.number = 5}};
  __dme2(f3) = {{.number = 5}};
  __dme2(g3) = {{.number = 5}};
  __dme2(h3) = {{.number = 5}};
  __dme2(i3) = {{.number = 5}};
  __dme2(j3) = {{.number = 5}};
  __dme2(k3) = {{.number = 5}};
  __dme2(l3) = {{.number = 5}};
  __dme2(m3) = {{.number = 5}};
  __dme2(n3) = {{.number = 5}};
  __dme2(o3) = {{.number = 5}};
  __dme2(p3) = {{.number = 5}};
  __dme2(q3) = {{.number = 5}};
  __dme2(r3) = {{.number = 5}};
  __dme2(s3) = {{.number = 5}};
  __dme2(t3) = {{.number = 5}};
  __dme2(u3) = {{.number = 5}};
  __dme2(v3) = {{.number = 5}};
  __dme2(w3) = {{.number = 5}};
  __dme2(x3) = {{.number = 5}};
  __dme2(y3) = {{.number = 5}};
  __dme2(z3) = {{.number = 5}};
  __dme2(a4) = {{.number = 5}};
  __dme2(b4) = {{.number = 5}};
  __dme2(c4) = {{.number = 5}};
  __dme2(d4) = {{.number = 5}};
  __dme2(e4) = {{.number = 5}};
  __dme2(f4) = {{.number = 5}};
  __dme2(g4) = {{.number = 5}};
  __dme2(h4) = {{.number = 5}};
  __dme2(i4) = {{.number = 5}};
  __dme2(j4) = {{.number = 5}};
  __dme2(k4) = {{.number = 5}};
  __dme2(l4) = {{.number = 5}};
  __dme2(m4) = {{.number = 5}};
  __dme2(n4) = {{.number = 5}};
  __dme2(o4) = {{.number = 5}};
  __dme2(p4) = {{.number = 5}};
  __dme2(q4) = {{.number = 5}};
  __dme2(r4) = {{.number = 5}};
  __dme2(s4) = {{.number = 5}};
  __dme2(t4) = {{.number = 5}};
  __dme2(u4) = {{.number = 5}};
  __dme2(v4) = {{.number = 5}};
  __dme2(w4) = {{.number = 5}};
  __dme2(x4) = {{.number = 5}};
  __dme2(y4) = {{.number = 5}};
  __dme2(z4) = {{.number = 5}};
  __dme2(a5) = {{.number = 5}};
  __dme2(b5) = {{.number = 5}};
  __dme2(c5) = {{.number = 5}};
  __dme2(d5) = {{.number = 5}};
  __dme2(e5) = {{.number = 5}};
  __dme2(f5) = {{.number = 5}};
  __dme2(g5) = {{.number = 5}};
  __dme2(h5) = {{.number = 5}};
  __dme2(i5) = {{.number = 5}};
  __dme2(j5) = {{.number = 5}};
  __dme2(k5) = {{.number = 5}};
  __dme2(l5) = {{.number = 5}};
  __dme2(m5) = {{.number = 5}};
  __dme2(n5) = {{.number = 5}};
  __dme2(o5) = {{.number = 5}};
  __dme2(p5) = {{.number = 5}};
  __dme2(q5) = {{.number = 5}};
  __dme2(r5) = {{.number = 5}};
  __dme2(s5) = {{.number = 5}};
  __dme2(t5) = {{.number = 5}};
  __dme2(u5) = {{.number = 5}};
  __dme2(v5) = {{.number = 5}};
  __dme2(w5) = {{.number = 5}};
  __dme2(x5) = {{.number = 5}};
  __dme2(y5) = {{.number = 5}};
  __dme2(z5) = {{.number = 5}};
  __dme2(a6) = {{.number = 5}};
  __dme2(b6) = {{.number = 5}};
  __dme2(c6) = {{.number = 5}};
  __dme2(d6) = {{.number = 5}};
  __dme2(e6) = {{.number = 5}};
  __dme2(f6) = {{.number = 5}};
  __dme2(g6) = {{.number = 5}};
  __dme2(h6) = {{.number = 5}};
  __dme2(i6) = {{.number = 5}};
  __dme2(j6) = {{.number = 5}};
  __dme2(k6) = {{.number = 5}};
  __dme2(l6) = {{.number = 5}};
  __dme2(m6) = {{.number = 5}};
  __dme2(n6) = {{.number = 5}};
  __dme2(o6) = {{.number = 5}};
  __dme2(p6) = {{.number = 5}};
  __dme2(q6) = {{.number = 5}};
  __dme2(r6) = {{.number = 5}};
  __dme2(s6) = {{.number = 5}};
  __dme2(t6) = {{.number = 5}};
  __dme2(u6) = {{.number = 5}};
  __dme2(v6) = {{.number = 5}};
  __dme2(w6) = {{.number = 5}};
  __dme2(x6) = {{.number = 5}};
  __dme2(y6) = {{.number = 5}};
  __dme2(z6) = {{.number = 5}};
  __dme2(a7) = {{.number = 5}};
  __dme2(b7) = {{.number = 5}};
  __dme2(c7) = {{.number = 5}};
  __dme2(d7) = {{.number = 5}};
  __dme2(e7) = {{.number = 5}};
  __dme2(f7) = {{.number = 5}};
  __dme2(g7) = {{.number = 5}};
  __dme2(h7) = {{.number = 5}};
  __dme2(i7) = {{.number = 5}};
  __dme2(j7) = {{.number = 5}};
  __dme2(k7) = {{.number = 5}};
  __dme2(l7) = {{.number = 5}};
  __dme2(m7) = {{.number = 5}};
  __dme2(n7) = {{.number = 5}};
  __dme2(o7) = {{.number = 5}};
  __dme2(p7) = {{.number = 5}};
  __dme2(q7) = {{.number = 5}};
  __dme2(r7) = {{.number = 5}};
  __dme2(s7) = {{.number = 5}};
  __dme2(t7) = {{.number = 5}};
  __dme2(u7) = {{.number = 5}};
  __dme2(v7) = {{.number = 5}};
  __dme2(w7) = {{.number = 5}};
  __dme2(x7) = {{.number = 5}};
  __dme2(y7) = {{.number = 5}};
  __dme2(z7) = {{.number = 5}};
  __dme2(a8) = {{.number = 5}};
  __dme2(b8) = {{.number = 5}};
  __dme2(c8) = {{.number = 5}};
  __dme2(d8) = {{.number = 5}};
  __dme2(e8) = {{.number = 5}};
  __dme2(f8) = {{.number = 5}};
  __dme2(g8) = {{.number = 5}};
  __dme2(h8) = {{.number = 5}};
  __dme2(i8) = {{.number = 5}};
  __dme2(j8) = {{.number = 5}};
  __dme2(k8) = {{.number = 5}};
  __dme2(l8) = {{.number = 5}};
  __dme2(m8) = {{.number = 5}};
  __dme2(n8) = {{.number = 5}};
  __dme2(o8) = {{.number = 5}};
  __dme2(p8) = {{.number = 5}};
  __dme2(q8) = {{.number = 5}};
  __dme2(r8) = {{.number = 5}};
  __dme2(s8) = {{.number = 5}};
  __dme2(t8) = {{.number = 5}};
  __dme2(u8) = {{.number = 5}};
  __dme2(v8) = {{.number = 5}};
  __dme2(w8) = {{.number = 5}};
  __dme2(x8) = {{.number = 5}};
  __dme2(y8) = {{.number = 5}};
  __dme2(z8) = {{.number = 5}};
  __dme2(a9) = {{.number = 5}};
  __dme2(b9) = {{.number = 5}};
  __dme2(c9) = {{.number = 5}};
  __dme2(d9) = {{.number = 5}};
  __dme2(e9) = {{.number = 5}};
  __dme2(f9) = {{.number = 5}};
  __dme2(g9) = {{.number = 5}};
  __dme2(h9) = {{.number = 5}};
  __dme2(i9) = {{.number = 5}};
  __dme2(j9) = {{.number = 5}};
  __dme2(k9) = {{.number = 5}};
  __dme2(l9) = {{.number = 5}};
  __dme2(m9) = {{.number = 5}};
  __dme2(n9) = {{.number = 5}};
  __dme2(o9) = {{.number = 5}};
  __dme2(p9) = {{.number = 5}};
  __dme2(q9) = {{.number = 5}};
  __dme2(r9) = {{.number = 5}};
  __dme2(s9) = {{.number = 5}};
  __dme2(t9) = {{.number = 5}};
  __dme2(u9) = {{.number = 5}};
  __dme2(v9) = {{.number = 5}};
  __dme2(w9) = {{.number = 5}};
  __dme2(x9) = {{.number = 5}};
  __dme2(y9) = {{.number = 5}};
  __dme2(z9) = {{.number = 5}};
  __dme2(a10) = {{.number = 5}};
};

struct dme2_t : dme_inherit__(dme2_t, data_we_want_t) {
  __dme2_data(a, int x;) = {{ .number = 105 }};
  __dme2_data(b, int x;) = {{ .number = 105 }};
  __dme2_data(c, int x;) = {{ .number = 105 }};
  __dme2_data(d, int x;) = {{ .number = 105 }};
  __dme2_data(e, int x;) = {{ .number = 105 }};
  __dme2_data(f, int x;) = {{ .number = 105 }};
  __dme2_data(g, int x;) = {{ .number = 105 }};
  __dme2_data(h, int x;) = {{ .number = 105 }};
  __dme2_data(i, int x;) = {{ .number = 105 }};
  __dme2_data(j, int x;) = {{ .number = 105 }};
  __dme2_data(k, int x;) = {{ .number = 105 }};
  __dme2_data(l, int x;) = {{ .number = 105 }};
  __dme2_data(m, int x;) = {{ .number = 105 }};
  __dme2_data(n, int x;) = {{ .number = 105 }};
  __dme2_data(o, int x;) = {{ .number = 105 }};
  __dme2_data(p, int x;) = {{ .number = 105 }};
  __dme2_data(q, int x;) = {{ .number = 105 }};
  __dme2_data(r, int x;) = {{ .number = 105 }};
  __dme2_data(s, int x;) = {{ .number = 105 }};
  __dme2_data(t, int x;) = {{ .number = 105 }};
  __dme2_data(u, int x;) = {{ .number = 105 }};
  __dme2_data(v, int x;) = {{ .number = 105 }};
  __dme2_data(w, int x;) = {{ .number = 105 }};
  __dme2_data(x, int x;) = {{ .number = 105 }};
  __dme2_data(y, int x;) = {{ .number = 105 }};
  __dme2_data(z, int x;) = {{ .number = 105 }};
  __dme2_data(a1, int x;) = {{ .number = 10 }};
  __dme2_data(b1, int x;) = {{ .number = 10 }};
  __dme2_data(c1, int x;) = {{ .number = 10 }};
  __dme2_data(d1, int x;) = {{ .number = 10 }};
  __dme2_data(e1, int x;) = {{ .number = 10 }};
  __dme2_data(f1, int x;) = {{ .number = 10 }};
  __dme2_data(g1, int x;) = {{ .number = 10 }};
  __dme2_data(h1, int x;) = {{ .number = 10 }};
  __dme2_data(i1, int x;) = {{ .number = 10 }};
  __dme2_data(j1, int x;) = {{ .number = 10 }};
  __dme2_data(k1, int x;) = {{ .number = 10 }};
  __dme2_data(l1, int x;) = {{ .number = 10 }};
  __dme2_data(m1, int x;) = {{ .number = 10 }};
  __dme2_data(n1, int x;) = {{ .number = 10 }};
  __dme2_data(o1, int x;) = {{ .number = 10 }};
  __dme2_data(p1, int x;) = {{ .number = 10 }};
  __dme2_data(q1, int x;) = {{ .number = 10 }};
  __dme2_data(r1, int x;) = {{ .number = 10 }};
  __dme2_data(s1, int x;) = {{ .number = 10 }};
  __dme2_data(t1, int x;) = {{ .number = 10 }};
  __dme2_data(u1, int x;) = {{ .number = 10 }};
  __dme2_data(v1, int x;) = {{ .number = 10 }};
  __dme2_data(w1, int x;) = {{ .number = 10 }};
  __dme2_data(x1, int x;) = {{ .number = 10 }};
  __dme2_data(y1, int x;) = {{ .number = 10 }};
  __dme2_data(z1, int x;) = {{ .number = 10 }};
  __dme2_data(a2, int x;) = {{ .number = 10 }};
  __dme2_data(b2, int x;) = {{ .number = 10 }};
  __dme2_data(c2, int x;) = {{ .number = 10 }};
  __dme2_data(d2, int x;) = {{ .number = 10 }};
  __dme2_data(e2, int x;) = {{ .number = 10 }};
  __dme2_data(f2, int x;) = {{ .number = 10 }};
  __dme2_data(g2, int x;) = {{ .number = 10 }};
  __dme2_data(h2, int x;) = {{ .number = 10 }};
  __dme2_data(i2, int x;) = {{ .number = 10 }};
  __dme2_data(j2, int x;) = {{ .number = 10 }};
  __dme2_data(k2, int x;) = {{ .number = 10 }};
  __dme2_data(l2, int x;) = {{ .number = 10 }};
  __dme2_data(m2, int x;) = {{ .number = 10 }};
  __dme2_data(n2, int x;) = {{ .number = 10 }};
  __dme2_data(o2, int x;) = {{ .number = 10 }};
  __dme2_data(p2, int x;) = {{ .number = 10 }};
  __dme2_data(q2, int x;) = {{ .number = 10 }};
  __dme2_data(r2, int x;) = {{ .number = 10 }};
  __dme2_data(s2, int x;) = {{ .number = 10 }};
  __dme2_data(t2, int x;) = {{ .number = 10 }};
  __dme2_data(u2, int x;) = {{ .number = 10 }};
  __dme2_data(v2, int x;) = {{ .number = 10 }};
  __dme2_data(w2, int x;) = {{ .number = 10 }};
  __dme2_data(x2, int x;) = {{ .number = 10 }};
  __dme2_data(y2, int x;) = {{ .number = 10 }};
  __dme2_data(z2, int x;) = {{ .number = 10 }};
  __dme2_data(a3, int x;) = {{ .number = 10 }};
  __dme2_data(b3, int x;) = {{ .number = 10 }};
  __dme2_data(c3, int x;) = {{ .number = 10 }};
  __dme2_data(d3, int x;) = {{ .number = 10 }};
  __dme2_data(e3, int x;) = {{ .number = 10 }};
  __dme2_data(f3, int x;) = {{ .number = 10 }};
  __dme2_data(g3, int x;) = {{ .number = 10 }};
  __dme2_data(h3, int x;) = {{ .number = 10 }};
  __dme2_data(i3, int x;) = {{ .number = 10 }};
  __dme2_data(j3, int x;) = {{ .number = 10 }};
  __dme2_data(k3, int x;) = {{ .number = 10 }};
  __dme2_data(l3, int x;) = {{ .number = 10 }};
  __dme2_data(m3, int x;) = {{ .number = 10 }};
  __dme2_data(n3, int x;) = {{ .number = 10 }};
  __dme2_data(o3, int x;) = {{ .number = 10 }};
  __dme2_data(p3, int x;) = {{ .number = 10 }};
  __dme2_data(q3, int x;) = {{ .number = 10 }};
  __dme2_data(r3, int x;) = {{ .number = 10 }};
  __dme2_data(s3, int x;) = {{ .number = 10 }};
  __dme2_data(t3, int x;) = {{ .number = 10 }};
  __dme2_data(u3, int x;) = {{ .number = 10 }};
  __dme2_data(v3, int x;) = {{ .number = 10 }};
  __dme2_data(w3, int x;) = {{ .number = 10 }};
  __dme2_data(x3, int x;) = {{ .number = 10 }};
  __dme2_data(y3, int x;) = {{ .number = 10 }};
  __dme2_data(z3, int x;) = {{ .number = 10 }};
  __dme2_data(a4, int x;) = {{ .number = 10 }};
  __dme2_data(b4, int x;) = {{ .number = 10 }};
  __dme2_data(c4, int x;) = {{ .number = 10 }};
  __dme2_data(d4, int x;) = {{ .number = 10 }};
  __dme2_data(e4, int x;) = {{ .number = 10 }};
  __dme2_data(f4, int x;) = {{ .number = 10 }};
  __dme2_data(g4, int x;) = {{ .number = 10 }};
  __dme2_data(h4, int x;) = {{ .number = 10 }};
  __dme2_data(i4, int x;) = {{ .number = 10 }};
  __dme2_data(j4, int x;) = {{ .number = 10 }};
  __dme2_data(k4, int x;) = {{ .number = 10 }};
  __dme2_data(l4, int x;) = {{ .number = 10 }};
  __dme2_data(m4, int x;) = {{ .number = 10 }};
  __dme2_data(n4, int x;) = {{ .number = 10 }};
  __dme2_data(o4, int x;) = {{ .number = 10 }};
  __dme2_data(p4, int x;) = {{ .number = 10 }};
  __dme2_data(q4, int x;) = {{ .number = 10 }};
  __dme2_data(r4, int x;) = {{ .number = 10 }};
  __dme2_data(s4, int x;) = {{ .number = 10 }};
  __dme2_data(t4, int x;) = {{ .number = 10 }};
  __dme2_data(u4, int x;) = {{ .number = 10 }};
  __dme2_data(v4, int x;) = {{ .number = 10 }};
  __dme2_data(w4, int x;) = {{ .number = 10 }};
  __dme2_data(x4, int x;) = {{ .number = 10 }};
  __dme2_data(y4, int x;) = {{ .number = 10 }};
  __dme2_data(z4, int x;) = {{ .number = 10 }};
  __dme2_data(a5, int x;) = {{ .number = 10 }};
  __dme2_data(b5, int x;) = {{ .number = 10 }};
  __dme2_data(c5, int x;) = {{ .number = 10 }};
  __dme2_data(d5, int x;) = {{ .number = 10 }};
  __dme2_data(e5, int x;) = {{ .number = 10 }};
  __dme2_data(f5, int x;) = {{ .number = 10 }};
  __dme2_data(g5, int x;) = {{ .number = 10 }};
  __dme2_data(h5, int x;) = {{ .number = 10 }};
  __dme2_data(i5, int x;) = {{ .number = 10 }};
  __dme2_data(j5, int x;) = {{ .number = 10 }};
  __dme2_data(k5, int x;) = {{ .number = 10 }};
  __dme2_data(l5, int x;) = {{ .number = 10 }};
  __dme2_data(m5, int x;) = {{ .number = 10 }};
  __dme2_data(n5, int x;) = {{ .number = 10 }};
  __dme2_data(o5, int x;) = {{ .number = 10 }};
  __dme2_data(p5, int x;) = {{ .number = 10 }};
  __dme2_data(q5, int x;) = {{ .number = 10 }};
  __dme2_data(r5, int x;) = {{ .number = 10 }};
  __dme2_data(s5, int x;) = {{ .number = 10 }};
  __dme2_data(t5, int x;) = {{ .number = 10 }};
  __dme2_data(u5, int x;) = {{ .number = 10 }};
  __dme2_data(v5, int x;) = {{ .number = 10 }};
  __dme2_data(w5, int x;) = {{ .number = 10 }};
  __dme2_data(x5, int x;) = {{ .number = 10 }};
  __dme2_data(y5, int x;) = {{ .number = 10 }};
  __dme2_data(z5, int x;) = {{ .number = 10 }};
  __dme2_data(a6, int x;) = {{ .number = 10 }};
  __dme2_data(b6, int x;) = {{ .number = 10 }};
  __dme2_data(c6, int x;) = {{ .number = 10 }};
  __dme2_data(d6, int x;) = {{ .number = 10 }};
  __dme2_data(e6, int x;) = {{ .number = 10 }};
  __dme2_data(f6, int x;) = {{ .number = 10 }};
  __dme2_data(g6, int x;) = {{ .number = 10 }};
  __dme2_data(h6, int x;) = {{ .number = 10 }};
  __dme2_data(i6, int x;) = {{ .number = 10 }};
  __dme2_data(j6, int x;) = {{ .number = 10 }};
  __dme2_data(k6, int x;) = {{ .number = 10 }};
  __dme2_data(l6, int x;) = {{ .number = 10 }};
  __dme2_data(m6, int x;) = {{ .number = 10 }};
  __dme2_data(n6, int x;) = {{ .number = 10 }};
  __dme2_data(o6, int x;) = {{ .number = 10 }};
  __dme2_data(p6, int x;) = {{ .number = 10 }};
  __dme2_data(q6, int x;) = {{ .number = 10 }};
  __dme2_data(r6, int x;) = {{ .number = 10 }};
  __dme2_data(s6, int x;) = {{ .number = 10 }};
  __dme2_data(t6, int x;) = {{ .number = 10 }};
  __dme2_data(u6, int x;) = {{ .number = 10 }};
  __dme2_data(v6, int x;) = {{ .number = 10 }};
  __dme2_data(w6, int x;) = {{ .number = 10 }};
  __dme2_data(x6, int x;) = {{ .number = 10 }};
  __dme2_data(y6, int x;) = {{ .number = 10 }};
  __dme2_data(z6, int x;) = {{ .number = 10 }};
  __dme2_data(a7, int x;) = {{ .number = 10 }};
  __dme2_data(b7, int x;) = {{ .number = 10 }};
  __dme2_data(c7, int x;) = {{ .number = 10 }};
  __dme2_data(d7, int x;) = {{ .number = 10 }};
  __dme2_data(e7, int x;) = {{ .number = 10 }};
  __dme2_data(f7, int x;) = {{ .number = 10 }};
  __dme2_data(g7, int x;) = {{ .number = 10 }};
  __dme2_data(h7, int x;) = {{ .number = 10 }};
  __dme2_data(i7, int x;) = {{ .number = 10 }};
  __dme2_data(j7, int x;) = {{ .number = 10 }};
  __dme2_data(k7, int x;) = {{ .number = 10 }};
  __dme2_data(l7, int x;) = {{ .number = 10 }};
  __dme2_data(m7, int x;) = {{ .number = 10 }};
  __dme2_data(n7, int x;) = {{ .number = 10 }};
  __dme2_data(o7, int x;) = {{ .number = 10 }};
  __dme2_data(p7, int x;) = {{ .number = 10 }};
  __dme2_data(q7, int x;) = {{ .number = 10 }};
  __dme2_data(r7, int x;) = {{ .number = 10 }};
  __dme2_data(s7, int x;) = {{ .number = 10 }};
  __dme2_data(t7, int x;) = {{ .number = 10 }};
  __dme2_data(u7, int x;) = {{ .number = 10 }};
  __dme2_data(v7, int x;) = {{ .number = 10 }};
  __dme2_data(w7, int x;) = {{ .number = 10 }};
  __dme2_data(x7, int x;) = {{ .number = 10 }};
  __dme2_data(y7, int x;) = {{ .number = 10 }};
  __dme2_data(z7, int x;) = {{ .number = 10 }};
  __dme2_data(a8, int x;) = {{ .number = 10 }};
  __dme2_data(b8, int x;) = {{ .number = 10 }};
  __dme2_data(c8, int x;) = {{ .number = 10 }};
  __dme2_data(d8, int x;) = {{ .number = 10 }};
  __dme2_data(e8, int x;) = {{ .number = 10 }};
  __dme2_data(f8, int x;) = {{ .number = 10 }};
  __dme2_data(g8, int x;) = {{ .number = 10 }};
  __dme2_data(h8, int x;) = {{ .number = 10 }};
  __dme2_data(i8, int x;) = {{ .number = 10 }};
  __dme2_data(j8, int x;) = {{ .number = 10 }};
  __dme2_data(k8, int x;) = {{ .number = 10 }};
  __dme2_data(l8, int x;) = {{ .number = 10 }};
  __dme2_data(m8, int x;) = {{ .number = 10 }};
  __dme2_data(n8, int x;) = {{ .number = 10 }};
  __dme2_data(o8, int x;) = {{ .number = 10 }};
  __dme2_data(p8, int x;) = {{ .number = 10 }};
  __dme2_data(q8, int x;) = {{ .number = 10 }};
  __dme2_data(r8, int x;) = {{ .number = 10 }};
  __dme2_data(s8, int x;) = {{ .number = 10 }};
  __dme2_data(t8, int x;) = {{ .number = 10 }};
  __dme2_data(u8, int x;) = {{ .number = 10 }};
  __dme2_data(v8, int x;) = {{ .number = 10 }};
  __dme2_data(w8, int x;) = {{ .number = 10 }};
  __dme2_data(x8, int x;) = {{ .number = 10 }};
  __dme2_data(y8, int x;) = {{ .number = 10 }};
  __dme2_data(z8, int x;) = {{ .number = 10 }};
};

#pragma pack(pop)

int main() {
  dme2_t c;
  c.b.AN();
  c.GetMemberAmount();

  dme_t a;
  dme_t b;

  //
#if DME_VERIFY_PRINT == 1
  printf("%llu %llu %llu %llu %d %d", a.a.I, b.a.I, b.z8.I, a.b.I, (int)a.z8, (int)c.c);
#endif

#if VERIFY_DME == 1
  assert(a.a.I == 0);
  assert(b.a.I == 0);
  assert((int)b.z8 == 233);
  assert((int)c.c == 2 && c.c.I == 2);
  assert((void*)c.NA(2) == (void*)&c.c);
  assert(c.GetMemberAmount() == sizeof(c) / sizeof(decltype(c)::dme_type_t));
  //decltype(c.d)::dt::;

  //printf("%s\n", typeid(std::tuple_element_t<0, std::tuple<decltype(a.b)::a_t>>).name());
#endif
  
  return a.a.I + b.a.I + b.z8 + a.b + a.z8 + c.c;
}
