/* this is seperate file because of mess */

#define NAL_UNKNOWN ETC_VEDC_CodecRelated_OpenH264_NAL_UNKNOWN
#define NAL_SLICE ETC_VEDC_CodecRelated_OpenH264_NAL_SLICE
#define NAL_SLICE_DPA ETC_VEDC_CodecRelated_OpenH264_NAL_SLICE_DPA
#define NAL_SLICE_DPB ETC_VEDC_CodecRelated_OpenH264_NAL_SLICE_DPB
#define NAL_SLICE_DPC ETC_VEDC_CodecRelated_OpenH264_NAL_SLICE_DPC
#define NAL_SLICE_IDR ETC_VEDC_CodecRelated_OpenH264_NAL_SLICE_IDR
#define NAL_SEI ETC_VEDC_CodecRelated_OpenH264_NAL_SEI
#define NAL_SPS ETC_VEDC_CodecRelated_OpenH264_NAL_SPS
#define NAL_PPS ETC_VEDC_CodecRelated_OpenH264_NAL_PPS
#define NAL_PRIORITY_DISPOSABLE ETC_VEDC_CodecRelated_OpenH264_NAL_PRIORITY_DISPOSABLE
#define NAL_PRIORITY_LOW ETC_VEDC_CodecRelated_OpenH264_NAL_PRIORITY_LOW
#define NAL_PRIORITY_HIGH ETC_VEDC_CodecRelated_OpenH264_NAL_PRIORITY_HIGH
#define NAL_PRIORITY_HIGHEST ETC_VEDC_CodecRelated_OpenH264_NAL_PRIORITY_HIGHEST
#include <wels/codec_api.h>
#undef NAL_UNKNOWN
#undef NAL_SLICE
#undef NAL_SLICE_DPA
#undef NAL_SLICE_DPB
#undef NAL_SLICE_DPC
#undef NAL_SLICE_IDR
#undef NAL_SEI
#undef NAL_SPS
#undef NAL_PPS
#undef NAL_PRIORITY_DISPOSABLE
#undef NAL_PRIORITY_LOW
#undef NAL_PRIORITY_HIGH
#undef NAL_PRIORITY_HIGHEST

#define NAL_UNKNOWN ETC_VEDC_CodecRelated_x264_NAL_UNKNOWN
#define NAL_SLICE ETC_VEDC_CodecRelated_x264_NAL_SLICE
#define NAL_SLICE_DPA ETC_VEDC_CodecRelated_x264_NAL_SLICE_DPA
#define NAL_SLICE_DPB ETC_VEDC_CodecRelated_x264_NAL_SLICE_DPB
#define NAL_SLICE_DPC ETC_VEDC_CodecRelated_x264_NAL_SLICE_DPC
#define NAL_SLICE_IDR ETC_VEDC_CodecRelated_x264_NAL_SLICE_IDR
#define NAL_SEI ETC_VEDC_CodecRelated_x264_NAL_SEI
#define NAL_SPS ETC_VEDC_CodecRelated_x264_NAL_SPS
#define NAL_PPS ETC_VEDC_CodecRelated_x264_NAL_PPS
#define NAL_PRIORITY_DISPOSABLE ETC_VEDC_CodecRelated_x264_NAL_PRIORITY_DISPOSABLE
#define NAL_PRIORITY_LOW ETC_VEDC_CodecRelated_x264_NAL_PRIORITY_LOW
#define NAL_PRIORITY_HIGH ETC_VEDC_CodecRelated_x264_NAL_PRIORITY_HIGH
#define NAL_PRIORITY_HIGHEST ETC_VEDC_CodecRelated_x264_NAL_PRIORITY_HIGHEST
#include <x264.h>
#undef NAL_UNKNOWN
#undef NAL_SLICE
#undef NAL_SLICE_DPA
#undef NAL_SLICE_DPB
#undef NAL_SLICE_DPC
#undef NAL_SLICE_IDR
#undef NAL_SEI
#undef NAL_SPS
#undef NAL_PPS
#undef NAL_PRIORITY_DISPOSABLE
#undef NAL_PRIORITY_LOW
#undef NAL_PRIORITY_HIGH
#undef NAL_PRIORITY_HIGHEST
